theme = "bogster"

[keys.normal]
"backspace" = {t = ":lsp-restart", s = ":lsp-stop"}
"F1" = {n = ":set soft-wrap.enable false", N = ":set soft-wrap.enable true", t = ":set smart-tab.enable false", T = ":set smart-tab.enable true"}
"F2" = {b = ":buffer-close", B = ":buffer-close!", a = ":buffer-close-all", A = ":buffer-close-all!"}
esc = ["collapse_selection", "keep_primary_selection"]

[editor]
scrolloff = 1
scroll-lines = 5
shell = ["nu", "-c"]
soft-wrap.enable = true
bufferline = "multiple"
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true
