[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[[language]]
name = "cpp"
auto-format = false
file-types = ["cpp", "h", "hpp"]
language-servers = ["clangd"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "lua"
indent = { tab-width = 4, unit = "    " }
